<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<title>Madokami.com &middot; {% block title %}Kawaii File Hosting{% endblock %}</title>
	<link rel="shortcut icon" href=favicon.ico type="image/x-icon">
	<link rel="stylesheet" href="pomf.min.css">
</head>
<body>
<div class="container">
	{% block body %}What the fuck are you doing here, baka?{% endblock %}
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53705363-3', 'auto');
  ga('send', 'pageview');
</script>
</body>
</html>
